### ISSUE TITLE
encount error parameters error 87

### ISSUE THREAD

**Issue by gonewind73** [alexsunday/pyvpn#1]
when test in windows, the statement encount error 87? how to work around it? 

 win32file.DeviceIoControl(handle, TAP_IOCTL_CONFIG_TUN,
                                  '\x0a\x03\x00\x01\x0a\x03\x00\x00\xff\xff\xff\x00', None)

**Comment by gonewind73** [comment]
it is my mistake.

**Comment by alexsunday** [comment]
cannot support win32, sorry, only running on linux.

**Comment by alexsunday** [comment]
I cannot found openvpn TUN/TAP documentation  for windows.
